---
language: node_js
node_js:
  - "5.1"

sudo: false

env:
  - CXX=g++-4.8

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - xvfb
      - libgnome-keyring-dev
      - g++-4.8

cache:
  directories:
    - node_modules

before_install:
  - "npm config set spin false"
  - "npm install -g grunt-cli"
  - "npm install -g bower"

install:
  - npm install
  - bower install
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &

script:
  - npm test
